- name: Create semaphore group
  group:
    name: semaphore
    gid: 5000
    state: present
  become: True

- name: Create semaphore user
  user:
    uid: 5000
    name: semaphore
    groups: 
    - semaphore
    - docker
    shell: /bin/bash
    create_home: yes
    append: yes
    state: present
  become: True

- name: Set ssh key for semaphore
  authorized_key:
    user: semaphore
    state: present
    manage_dir: yes
    key: "{{ lookup('file', 'files/jingkai_rsa.pub') }}"
  become: True

- name: Install docker-compose python package
  remote_user: semaphore
  ansible.builtin.pip:
    name: 
    - docker
    - docker-compose
  
- name: Prepare semaphore folder
  file:
    path: /semaphore
    state: directory
    group: semaphore
    owner: semaphore
  become: True

- name: Copy semaphore-config
  copy:
    src: semaphore-config.json
    dest: /semaphore/semaphore-config.json
    decrypt: yes
    owner: semaphore 
    group: docker 
    mode: 777
    backup: no
  become: True

- name: Copy semaphore env
  copy:
    src: semaphore.env
    dest: /semaphore/semaphore.env
    decrypt: yes
    owner: semaphore 
    group: docker 
    mode: 777
    backup: no
  become: True


- name: Copy semaphore-postgres env
  copy:
    src: semaphore-postgres.env
    dest: /semaphore/semaphore-postgres.env
    decrypt: yes
    owner: semaphore 
    group: docker 
    mode: 777
    backup: no
  become: True

- name: Copy semaphore-compose yaml
  copy:
    src: semaphore-compose.yaml
    dest: /semaphore/semaphore-compose.yaml
    owner: semaphore 
    group: docker 
    mode: 777
    backup: no
  become: True
