version: "3.9"

services:
  caddy:
    container_name: caddy
    image: ghcr.io/xlanor/mirror-caddy-base:1.0.0
    restart: unless-stopped
    env_file:
      - /caddy/caddy.env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /caddy/Caddyfile:/etc/caddy/Caddyfile
      - /caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  default:
    name: services
    external: true